/*
 * chatDlg.java
 *
 * Created on April 6, 2008, 2:04 PM
 */

package magnum;

import java.awt.Font;
import java.io.DataInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTextArea;
import net.jxta.endpoint.Message;
import net.jxta.endpoint.MessageElement;
import net.jxta.endpoint.StringMessageElement;
import net.jxta.pipe.PipeMsgEvent;
import net.jxta.pipe.PipeMsgListener;
import net.jxta.util.JxtaBiDiPipe;
import org.jdesktop.application.Action;
import javax.swing.JFrame;
import net.jxta.peer.PeerID;

/**
 *
 * @author  fireball
 */
public class chatDlg extends javax.swing.JDialog implements Runnable{
    
    /** Creates new form chatDlg */
    JxtaBiDiPipe mybidipipe=null;
    int tableIndex;
    String sendername;
    boolean chk;
    Message newmsg = new Message();
    String Chattext_NameSpace="Chat text";
    String Block_Namespace="Blocked";
    public chatDlg(java.awt.Frame parent, boolean modal,JxtaBiDiPipe mybidipipe,String sendername) {
       super(parent,"Chat with "+sendername, modal);
       this.sendername=sendername;
       this.mybidipipe=mybidipipe;
       this.mybidipipe.setMessageListener(myPipelistener);
       PeerID remoteId =mybidipipe.getRemotePeerAdvertisement().getPeerID();
       for(int i=0;i<Dataframe.chattablemodel.getRowCount();i++)
       {
           if(remoteId.equals(Dataframe.chattablemodel.getValueAt(i, Dataframe.PeerId)))
           {
            tableIndex=i;
            break;
           }
       }
       initComponents();
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 200));
        setName("Chat"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(magnum.MagnumApp.class).getContext().getActionMap(chatDlg.class, this);
        jButton1.setAction(actionMap.get("btnChatDlg")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(magnum.MagnumApp.class).getContext().getResourceMap(chatDlg.class);
        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setName("jTextArea2"); // NOI18N
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setText("Block "+this.sendername);
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(194, 194, 194))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        newmsg.clear();
        
        Dataframe.chattablemodel.setValueAt(true, tableIndex, Dataframe.Blocked);
        MessageElement respElement = new StringMessageElement(Chattext_NameSpace,"", null);
        newmsg.addMessageElement(respElement);
        
        MessageElement blockElement = new StringMessageElement(Block_Namespace, Block_Namespace, null);
                newmsg.addMessageElement(blockElement);
                try{
             mybidipipe.sendMessage(newmsg);
             mybidipipe.close();
                      } catch (IOException ex) {
                Logger.getLogger(chatDlg.class.getName()).log(Level.SEVERE, null, ex);
            }    
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
    
    /**
     * @param args the command line arguments
     */
               
             
    public PipeMsgListener myPipelistener=new PipeMsgListener() {

        public void pipeMsgEvent(PipeMsgEvent event) {
              Message mymsg=event.getMessage();
               String temp=mymsg.getMessageElement(Chattext_NameSpace).toString();
               String blockmsg=mymsg.getMessageElement(Block_Namespace).toString();
               if(blockmsg.equals(Block_Namespace)){
                try {


                    jTextArea1.append("\n" + sendername + ":CHAT HAS BEEN CLOSED \n PLEASE CLOSE YOR DIALOG");
                    mybidipipe.close();
                    jButton1.setEnabled(false);

                    Thread.sleep(2000);
                    //Thread.currentThread().destroy();
                     Thread.currentThread().stop();
                    //Thread.currentThread().suspend();
                } catch (InterruptedException ex) {
                    Logger.getLogger(chatDlg.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(chatDlg.class.getName()).log(Level.SEVERE, null, ex);
                }
                    
                    //Thread.sleep(2000);
                    //Thread.currentThread().destroy();
                   // Thread.currentThread().stop();
                    //Thread.currentThread().suspend();
                   
                           
               
               }
              
               else
               
               jTextArea1.append("\n"+sendername+": "+temp);
        }
    };

 
   
   boolean flag=false;
    @Action
    public void btnChatDlg() {
        if(jTextArea2.getText().trim().length()>0)
        {
            try {
                           
                String data = jTextArea2.getText();
                newmsg.clear();
                MessageElement respElement = new StringMessageElement(Chattext_NameSpace, data, null);
                newmsg.addMessageElement(respElement);
                MessageElement blockElement = new StringMessageElement(Block_Namespace,"", null);
                newmsg.addMessageElement(blockElement);
                System.out.println(mybidipipe.sendMessage(newmsg));
                jTextArea1.append("\nMe:- "+data);
                
                Dataframe.chattablemodel.setValueAt(jTextArea1,tableIndex, Dataframe.ChatMsg);
                jTextArea2.setText("");
            //    mybidipipe.close();
            } catch (IOException ex) {
                Logger.getLogger(chatDlg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
            } 
      
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables

    public void run() {
     
        jTextArea1.setFocusable(true);
        this.setVisible(true);
       
    }

   
    

}